export interface Challenge {
  id: number;
  title: string;
  description: string;
  tip: string;
  difficulty: 'easy' | 'medium' | 'hard' | 'chaos';
  mode: 'practice' | 'game' | 'both';
  category: 'shot-restriction' | 'scoring' | 'movement' | 'tactical' | 'communication' | 'fun';
  icon: string;
  duration: string;
}

export const challenges: Challenge[] = [
  // ===== PRACTICE MODE =====
  // Shot Restriction — Easy
  {
    id: 1,
    title: 'No Smash Zone',
    description: 'No smashing for the entire drill. Focus on bandeja, vibora, and placement instead.',
    tip: 'This is how you develop touch on your overheads. Most club players over-smash.',
    difficulty: 'easy',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '🚫',
    duration: '10 minutes',
  },
  {
    id: 2,
    title: 'Lob City',
    description: 'Every third shot you hit must be a lob. No exceptions.',
    tip: 'Forces you to practice deep lobs under pressure, not just when it\'s comfortable.',
    difficulty: 'easy',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '🌈',
    duration: '10 minutes',
  },
  {
    id: 3,
    title: 'Slice Only',
    description: 'No flat shots allowed. Everything must have slice or backspin.',
    tip: 'Develops touch and control. Slice is the foundation of padel.',
    difficulty: 'easy',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '🔪',
    duration: '15 minutes',
  },
  {
    id: 4,
    title: 'Backhand World',
    description: 'You can only hit backhands. If the ball comes to your forehand, reposition or let your partner take it.',
    tip: 'Most players avoid their backhand. This forces you to build confidence on it.',
    difficulty: 'easy',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '✋',
    duration: '10 minutes',
  },
  // Shot Restriction — Medium
  {
    id: 5,
    title: 'No Volley Zone',
    description: 'You can\'t hit volleys. Every ball must bounce before you hit it.',
    tip: 'Teaches you to read the ball off the glass and develop your back-court game.',
    difficulty: 'medium',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '⛔',
    duration: '10 minutes',
  },
  {
    id: 6,
    title: 'Glass Master',
    description: 'You must let the ball hit the back glass before returning it when heading towards the glass. Don\'t cut it off early.',
    tip: 'Most players are afraid of the glass. This drill forces you to learn the bounces and timing.',
    difficulty: 'medium',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '🪟',
    duration: '15 minutes',
  },
  {
    id: 7,
    title: 'Soft Hands Only',
    description: 'No shot can be hit harder than 50% power. Everything must be touch and placement.',
    tip: 'Power is easy. Placement wins matches. This teaches you to construct points with precision.',
    difficulty: 'medium',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '🤲',
    duration: '15 minutes',
  },
  {
    id: 8,
    title: 'Cross Court Only',
    description: 'Every shot must go cross court. No straight shots allowed.',
    tip: 'Cross court is the safer, higher-percentage shot. This builds the habit of playing smart angles.',
    difficulty: 'medium',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '↗️',
    duration: '10 minutes',
  },
  {
    id: 9,
    title: 'Feed the Backhand',
    description: 'Every shot must be aimed at your opponent\'s backhand side.',
    tip: 'In a real match, targeting the weaker side wins points. This trains your accuracy under pressure.',
    difficulty: 'medium',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '🎯',
    duration: '10 minutes',
  },
  // Shot Restriction — Hard
  {
    id: 10,
    title: 'No Glass Allowed',
    description: 'You cannot use the back glass at all. If the ball passes you and hits the glass, you\'ve lost the point.',
    tip: 'Forces aggressive positioning. You must cut off every ball early, which builds fast reactions and anticipation.',
    difficulty: 'hard',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '🧱',
    duration: '10 minutes',
  },
  {
    id: 11,
    title: 'The Minimalist',
    description: 'You can only use 3 types of shots for the entire drill. Choose which 3 before starting.',
    tip: 'Reveals which shots you actually depend on and forces creativity with limited tools.',
    difficulty: 'hard',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '3️⃣',
    duration: '15 minutes',
  },
  {
    id: 12,
    title: 'Non-Dominant Hand',
    description: 'Play with your non-dominant hand for the entire drill.',
    tip: 'Develops coordination and gives you a new appreciation for footwork and positioning.',
    difficulty: 'hard',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '🫲',
    duration: '10 minutes',
  },
  // Shot Restriction — Chaos
  {
    id: 13,
    title: 'Mirror Mode',
    description: 'Whatever shot type your opponent hits, you must respond with the same type. They lob, you lob. They smash, you smash.',
    tip: 'Builds reactive shot variety and forces you out of your comfort patterns.',
    difficulty: 'chaos',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '🪞',
    duration: '10 minutes',
  },
  {
    id: 14,
    title: 'One Bounce Max',
    description: 'The ball can only bounce once on your side. If it bounces twice, you lose the point even if it\'s technically still in play.',
    tip: 'Develops explosive first-step speed and anticipation. No ball is allowed to die.',
    difficulty: 'chaos',
    mode: 'practice',
    category: 'shot-restriction',
    icon: '⚡',
    duration: '10 minutes',
  },
  // Movement — Easy
  {
    id: 15,
    title: 'Sticky Feet',
    description: 'After hitting the ball, you must freeze for 1 full second before moving again.',
    tip: 'Forces you to place the ball well because you can\'t rely on recovery. If your shot is bad, you\'re stuck.',
    difficulty: 'easy',
    mode: 'practice',
    category: 'movement',
    icon: '🧊',
    duration: '10 minutes',
  },
  {
    id: 16,
    title: 'The Rotation',
    description: 'After every point, you and your partner switch sides (left to right, right to left).',
    tip: 'Makes you comfortable on both sides. Most players get stuck on "their side."',
    difficulty: 'easy',
    mode: 'practice',
    category: 'movement',
    icon: '🔁',
    duration: '1 set',
  },
  // Movement — Medium
  {
    id: 17,
    title: 'No Man\'s Land',
    description: 'You cannot stand between the service line and the net. You\'re either fully at the net or fully at the back.',
    tip: 'Eliminates the bad habit of floating in no man\'s land. Commit to your position.',
    difficulty: 'medium',
    mode: 'practice',
    category: 'movement',
    icon: '🚧',
    duration: '15 minutes',
  },
  {
    id: 18,
    title: 'Shadow Play',
    description: 'You and your partner must always be within 2 meters of each other. Move as a unit.',
    tip: 'Develops team movement. The best padel pairs move together like they\'re connected by a rope.',
    difficulty: 'medium',
    mode: 'practice',
    category: 'movement',
    icon: '👥',
    duration: '10 minutes',
  },
  // Movement — Hard
  {
    id: 19,
    title: 'Solo Mission',
    description: 'One player covers the entire court alone for one game, then switch.',
    tip: 'Builds fitness, shot selection, and teaches you exactly how much court one player can cover.',
    difficulty: 'hard',
    mode: 'practice',
    category: 'movement',
    icon: '🦸',
    duration: '4 games (2 each)',
  },

  // ===== GAME MODE =====
  // Scoring — Easy
  {
    id: 20,
    title: 'Love-30 Start',
    description: 'The serving team starts every service game down love-30. Can they fight back?',
    tip: 'Makes every service game intense. Great equalizer when skill levels are slightly different.',
    difficulty: 'easy',
    mode: 'game',
    category: 'scoring',
    icon: '📉',
    duration: '1 set',
  },
  {
    id: 21,
    title: 'Bonus Lob',
    description: 'If you win a point with a lob that lands in the last meter of the court, it counts as 2 points.',
    tip: 'Rewards precision lobbing, which is one of the most underrated skills in padel.',
    difficulty: 'easy',
    mode: 'game',
    category: 'scoring',
    icon: '⭐',
    duration: '1 set',
  },
  {
    id: 22,
    title: 'Deuce Starts',
    description: 'Every game starts at deuce (40-40). Win by 2.',
    tip: 'Every single game is a pressure situation. Great for building clutch performance.',
    difficulty: 'easy',
    mode: 'game',
    category: 'scoring',
    icon: '⚖️',
    duration: '1 set',
  },
  // Scoring — Medium
  {
    id: 23,
    title: 'Golden Point',
    description: 'Every game is decided by a single point. First point wins the game. Best of 7 games wins the set.',
    tip: 'Forces maximum focus from the first second. No room for slow starts.',
    difficulty: 'medium',
    mode: 'game',
    category: 'scoring',
    icon: '🥇',
    duration: 'Best of 7',
  },
  {
    id: 24,
    title: 'No Second Serve',
    description: 'You only get one serve. Miss it and you lose the point.',
    tip: 'Makes the serve a high-stakes moment every time. Builds serve reliability under pressure.',
    difficulty: 'medium',
    mode: 'game',
    category: 'scoring',
    icon: '1️⃣',
    duration: '1 set',
  },
  {
    id: 25,
    title: 'Ace Jackpot',
    description: 'If you serve an ace, you win the entire game instantly. Not just the point.',
    tip: 'Makes everyone pay more attention to the serve and return. Adds drama.',
    difficulty: 'medium',
    mode: 'game',
    category: 'scoring',
    icon: '🎰',
    duration: '1 set',
  },
  // Scoring — Hard
  {
    id: 26,
    title: 'Countdown',
    description: 'The serving team starts at 40-0 advantage. But every point they lose counts double.',
    tip: 'Teaches you to protect a lead and stay focused when ahead.',
    difficulty: 'hard',
    mode: 'game',
    category: 'scoring',
    icon: '⏳',
    duration: '1 set',
  },
  {
    id: 27,
    title: 'Rally Tax',
    description: 'If a rally goes over 10 shots and you win it, the point counts double.',
    tip: 'Rewards patience and consistency. Discourages going for risky winners too early.',
    difficulty: 'hard',
    mode: 'game',
    category: 'scoring',
    icon: '💰',
    duration: '1 set',
  },
  // Tactical — Easy
  {
    id: 28,
    title: 'Target Practice',
    description: 'Before each point, call out loud which corner you\'re aiming for on your first shot. Bonus point if you hit it.',
    tip: 'Builds intentional shot placement instead of just reacting.',
    difficulty: 'easy',
    mode: 'game',
    category: 'tactical',
    icon: '🎯',
    duration: '1 set',
  },
  {
    id: 29,
    title: 'Approach and Conquer',
    description: 'If you hit a shot from behind the service line, you must move towards the net immediately after.',
    tip: 'Breaks the habit of staying back. Forces you to take the net and be aggressive.',
    difficulty: 'easy',
    mode: 'game',
    category: 'tactical',
    icon: '🏃',
    duration: '1 set',
  },
  // Tactical — Medium
  {
    id: 30,
    title: 'Net Winners Only',
    description: 'You can only win a point at the net. No winners from behind the service line count.',
    tip: 'Teaches point construction. You have to build the point and earn your way to the net.',
    difficulty: 'medium',
    mode: 'game',
    category: 'tactical',
    icon: '🏗️',
    duration: '1 set',
  },
  {
    id: 31,
    title: 'Australian Only',
    description: 'Both teams must play Australian formation for every service game. Server\'s partner stands on the same side.',
    tip: 'Develops poaching skills, cross-court returns, and formation play.',
    difficulty: 'medium',
    mode: 'game',
    category: 'tactical',
    icon: '🦘',
    duration: '1 set',
  },
  // Tactical — Hard
  {
    id: 32,
    title: '3-Shot Build',
    description: 'Each rally must last at least 3 shots before anyone can go for a winner. Early winners give the point to the opponent.',
    tip: 'Forces patient point construction. Stops the habit of going for winners on the first opportunity.',
    difficulty: 'hard',
    mode: 'game',
    category: 'tactical',
    icon: '🧠',
    duration: '1 set',
  },
  // Communication — Easy
  {
    id: 33,
    title: 'Coach Mode',
    description: 'Between every point, tell your partner one thing they did well. Out loud.',
    tip: 'Builds positive communication habits. The best partnerships are built on encouragement.',
    difficulty: 'easy',
    mode: 'game',
    category: 'communication',
    icon: '🗣️',
    duration: '1 set',
  },
  {
    id: 34,
    title: 'Call It',
    description: 'Before every serve, the serving team must briefly discuss their plan for the point. Out loud, opponents can hear.',
    tip: 'Forces intentional play. Even if the opponent hears, having a plan beats not having one.',
    difficulty: 'easy',
    mode: 'game',
    category: 'communication',
    icon: '📋',
    duration: '1 set',
  },
  // Communication — Medium
  {
    id: 35,
    title: 'Silent Game',
    description: 'Zero communication with your partner. No talking, no hand signals, no eye contact. Play on instinct.',
    tip: 'Develops court awareness and the ability to read your partner\'s movement without words.',
    difficulty: 'medium',
    mode: 'game',
    category: 'communication',
    icon: '🤐',
    duration: '1 set',
  },
  // Communication — Hard
  {
    id: 36,
    title: 'Swap Captain',
    description: 'One player is the "captain" each game. The captain decides formation and calls the shots. Swap every game.',
    tip: 'Forces both players to think tactically, not just the dominant personality.',
    difficulty: 'hard',
    mode: 'game',
    category: 'communication',
    icon: '👑',
    duration: '1 set',
  },
  // Fun / Wild Card
  {
    id: 37,
    title: 'Wrong Side',
    description: 'Right-side player plays left, left-side player plays right. Stay on your wrong side for the entire set.',
    tip: 'Builds versatility and helps you understand your partner\'s perspective.',
    difficulty: 'easy',
    mode: 'game',
    category: 'fun',
    icon: '🔄',
    duration: '1 set',
  },
  {
    id: 38,
    title: 'Opposite Day',
    description: 'If you normally serve first, serve second. If you normally play right, play left. Everything is reversed.',
    tip: 'Takes you out of your routine. Growth comes from discomfort.',
    difficulty: 'medium',
    mode: 'game',
    category: 'fun',
    icon: '🙃',
    duration: '1 set',
  },
  {
    id: 39,
    title: 'Celebrity Mode',
    description: 'After every point you WIN, you must celebrate like you just won the World Padel Tour finals. Full commitment.',
    tip: 'Builds energy and team spirit. Celebrations are underrated in padel.',
    difficulty: 'easy',
    mode: 'game',
    category: 'fun',
    icon: '🏆',
    duration: '1 set',
  },
  {
    id: 40,
    title: 'Speed Round',
    description: 'Serve within 5 seconds of the last point ending. No breaks, no tactical discussions. Just play.',
    tip: 'Builds rhythm and quick decision-making. Stops over-thinking between points.',
    difficulty: 'medium',
    mode: 'game',
    category: 'fun',
    icon: '💨',
    duration: '1 set',
  },
  {
    id: 41,
    title: 'The Jinx',
    description: 'If you and your partner say the same word at the same time, you lose the current point.',
    tip: 'No skill benefit. Just pure entertainment and paranoia.',
    difficulty: 'chaos',
    mode: 'game',
    category: 'fun',
    icon: '🤭',
    duration: '1 set',
  },
  {
    id: 42,
    title: 'Ball Hog',
    description: 'One designated player must take every ball they can physically reach, even if it\'s clearly their partner\'s. Swap every 2 games.',
    tip: 'For the ball hog: builds court coverage. For the partner: builds patience and forgiveness.',
    difficulty: 'hard',
    mode: 'game',
    category: 'fun',
    icon: '🐷',
    duration: '1 set',
  },
  {
    id: 43,
    title: 'The Commentator',
    description: 'One player per team must narrate the point out loud while playing. Swap commentators every game.',
    tip: 'Absolutely no skill benefit. Maximum entertainment.',
    difficulty: 'chaos',
    mode: 'game',
    category: 'fun',
    icon: '🎙️',
    duration: '1 set',
  },
  {
    id: 44,
    title: 'No Smash Zone (Game)',
    description: 'Neither team can smash for the entire set. Bandejas, viboras, and placement only.',
    tip: 'In Game Mode, this is fair because it applies to both teams. Develops patient overhead play.',
    difficulty: 'medium',
    mode: 'game',
    category: 'shot-restriction',
    icon: '🚫',
    duration: '1 set',
  },
];

export const DIFFICULTY_COLORS: Record<Challenge['difficulty'], string> = {
  easy: '#10B981',
  medium: '#F59E0B',
  hard: '#EF4444',
  chaos: '#8B5CF6',
};
