-- PR 10c-a1 ACL REPAIR — forward-only lockdown of the digest tables + ledger identity sequence.
-- Do NOT edit the deployed 20261002100000. It revoked ALL from PUBLIC/anon/authenticated but NOT from
-- service_role, so Supabase's `ALTER DEFAULT PRIVILEGES … GRANT ALL … TO service_role` left service_role
-- with DELETE + TRUNCATE (TRUNCATE bypasses the lifecycle triggers) on all eight tables — and left the
-- ledger identity sequence with USAGE for anon/authenticated + full privileges for service_role. This
-- migration strips ALL from every role and re-grants exactly the intended minimum. NO role gets table
-- DELETE / TRUNCATE / REFERENCES / TRIGGER; deletion happens ONLY via purge_notification_digest()
-- (owner privilege) + its FK cascades. The RPC grants (purge/link = service_role EXECUTE only) are
-- unaffected — this migration does not touch functions.

-- 1. strip the default-privilege grant from EVERY role (incl service_role) on all eight tables.
DO $acl$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'notification_worker_runs','notification_digest_groups','notification_digest_attempts',
    'notification_digest_group_attempts','notification_provider_events','notification_provider_circuit',
    'notification_send_counters','notification_send_reservations'] LOOP
    EXECUTE format('REVOKE ALL ON TABLE public.%I FROM PUBLIC, anon, authenticated, service_role', t);
  END LOOP;
END $acl$;

-- 2. re-grant exactly the intended minimum to service_role (never DELETE/TRUNCATE/REFERENCES/TRIGGER).
--    append-only audit tables: INSERT/SELECT only.
GRANT INSERT, SELECT ON public.notification_digest_group_attempts TO service_role;
GRANT INSERT, SELECT ON public.notification_provider_events        TO service_role;
--    mutable/state tables: INSERT/SELECT/UPDATE (the state machine mutates rows; retention deletes as owner).
GRANT INSERT, SELECT, UPDATE ON public.notification_digest_attempts    TO service_role;
GRANT INSERT, SELECT, UPDATE ON public.notification_worker_runs        TO service_role;
GRANT INSERT, SELECT, UPDATE ON public.notification_digest_groups      TO service_role;
GRANT INSERT, SELECT, UPDATE ON public.notification_provider_circuit   TO service_role;
GRANT INSERT, SELECT, UPDATE ON public.notification_send_counters      TO service_role;
GRANT INSERT, SELECT, UPDATE ON public.notification_send_reservations  TO service_role;

-- 3. lock down the ledger identity sequence (seq bigint GENERATED BY DEFAULT AS IDENTITY): only
--    service_role USAGE is needed for nextval() on a ledger INSERT — no SELECT/UPDATE, nothing to anon/auth.
REVOKE ALL ON SEQUENCE public.notification_digest_group_attempts_seq_seq FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE ON SEQUENCE public.notification_digest_group_attempts_seq_seq TO service_role;
